[project]
name = "ppocrv5-onnx"
version = "1.1.0"
description = "PP-OCRv5/PP-OCRv6 ONNX runtime with uv"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "onnxruntime; platform_system != 'Linux' or platform_machine != 'x86_64'",
  "onnxruntime==1.*; platform_system == 'Linux' and platform_machine == 'x86_64'",
  "opencv-python",
  "numpy",
  "omegaconf",
  "loguru",
  "matplotlib",
  "shapely",
  "pyclipper",
]

[build-system]
requires = ["setuptools>=62"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["ppocrv5_onnx", "ppocrv5_onnx.*"]
namespaces = false

[tool.setuptools.package-data]
ppocrv5_onnx = [
  "data/dict/ppocrv5_dict.txt",
  "data/dict/ppocrv6_dict.txt",
  "data/fonts/simfang.ttf",
]
